### ISSUE TITLE
Custom functions

### ISSUE THREAD

**Issue by Horus125** [fkleon/math-expressions#11]
Is it possible to create expressions from string containing custom functions and evaluate them? I'm trying to introduce inverse trygonometric functions and I'd like to evaluate "1+asin(0.5)" just like I can for example "1+sin(30)"

**Comment by fkleon** [comment]
Hi @Horus125 

Custom functions are currently somewhat limited in terms of usability. It's only possible to define and use custom functions programmatically, and the expression parser will not be able to recognise those functions. I've added some relevant examples and additional documentation in #12.

I've also added arcsin, arccos and arctan as default functions to this library in #13. That might help you if you're just after those particular inverse trigonometric functions. Please feel free to implement any other missing functions and submit a pull request, I'm always happy to accept contributions!
