### ISSUE TITLE
A problem with logarithm

### ISSUE THREAD

**Issue by lucas-daniel-sm** [fkleon/math-expressions#20]
I created an expression with a logarithm, but the logarithms were replaced by negative numbers.
Example: 
this expression: `Parser().parse('log_{10.0}({x}) - log_{10.0}({y}) / log_{10.0}({2.0})');` was changed to this: `'log_{10.0}({-x}) - log_{10.0}({-y}) / log_{10.0}({-2.0})'`

**Comment by fkleon** [comment]
Hi, thanks for this report.

There are two issues here:
* A shortcoming of the current parser implementation where the token `_` is parsed as unary minus.
* The string representation of a logarithm expression not being compatible with the parser.

The logarithm of x to base b is implemented as a function with two parameters where the first parameter is the base of the logarithm, and the second parameter is the number.

In the parser, the supported expression for log<sub>b</sub>(x) is `log(b, x)`.
I note that this is inconsistent with the `toString()` representation of a logarithm expression which is `log_{b}(x)`.

I'm going to review the existing `toString()` implementations and will make sure that they are compatible with the existing parser.

**Comment by fkleon** [comment]
I've released version 2.0.0 of math_expressions to pub. Shout out if that doesn't solve the issue.
