### ISSUE TITLE
How do I add a custom function to the context model?

### ISSUE THREAD

**Issue by vighnesh153** [fkleon/math-expressions#24]
Let's say I have an expression `MyFunc(123)` and I have implemented a function `double MyFunc(double)`. How do I attach this to the context model?

**Comment by fkleon** [comment]
Hi @vighnesh153 

Custom functions are somewhat limited, and can only be bound to mathematical expressions but not arbitrary Dart functions. They can only be defined programmatically and are not supported in the parser.

There are a few examples here:
* https://github.com/fkleon/math-expressions/blob/bb37ee4d1b0bdee5794b5832ecbf7e1f34d291f8/example/main.dart#L75
* https://github.com/fkleon/math-expressions/blob/bb37ee4d1b0bdee5794b5832ecbf7e1f34d291f8/test/expression_test_set.dart#L1145

Hope this helps. Let me know if you have any further questions.

**Comment by vighnesh153** [comment]
Okay. That makes sense. Thank you for your help.
