### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by albertodev01** [fkleon/math-expressions#37]
Hello!

Some packages of mine depend on `math_expressions` and it's working very well.
We were wondering if you were going to start the NNBD migration soon. Would you also need any help with it?

Regards,
Alberto

**Comment by fkleon** [comment]
Hi Alberto, thanks for raising this.

I have no immediate plans to work on this, but would welcome a contribution if you'd like to help out.

**Comment by albertodev01** [comment]
It has to be done, sooner or later! 😄 

I am busy with my own packages, if you're ok with it I'll help migrating the latest version during xmas holidays! Since they're going to be veery long due to the lockdown...

**Comment by fkleon** [comment]
Great, I might be able to look into it before. I'll update this ticket if I do.

**Comment by albertodev01** [comment]
I tried to migrate you package to nnbd! Could you please add me as contributor? In this way I can open a the new `null_safety` branch and open a PR!

**Comment by fkleon** [comment]
Thanks, that was quick! You should be able to open a pull request from an fork of this repository.

**Comment by albertodev01** [comment]
Yes I opened PR#38

**Comment by IchordeDionysos** [comment]
The new Dart version with null-safety was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by fkleon** [comment]
@IchordeDionysos Thank you, I'll try to pick this up as soon as I find some spare time. Looks like @albertodev01 abandoned their PR.

**Comment by albertodev01** [comment]
Yes sorry I don't have much time to work in this anymore! :(

**Comment by bigbang489** [comment]
Any updates?

**Comment by fkleon** [comment]
Should have a null safe prerelease out later today

**Comment by fkleon** [comment]
Have published `2.1.0-nullsafety.0`, can you give that a try?
I'll promote it to stable in a while if nobody reports any issues.

**Comment by bigbang489** [comment]
> Have published `2.1.0-nullsafety.0`, can you give that a try?
> I'll promote it to stable in a while if nobody reports any issues.
Thank you for your quick update, I will give it a try a let you know the result on tomorrow

**Comment by bigbang489** [comment]
> Have published `2.1.0-nullsafety.0`, can you give that a try?
> I'll promote it to stable in a while if nobody reports any issues.

I tested version 2.1.0-nullsafety.0 in my production. No issue found yet
