### ISSUE TITLE
Sign handled Incorrectly with Exponentiation

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [fkleon/math-expressions#41]
First of all: thanks for this repo ❤️ This is an awesome package ✨ 

## Problem

This is a pretty simple problem to understanding:

Say we have the following expression: **`-x^2`**.  
Here is how that expression is understood:

* In mathematics: `-(x^2)`.
* In `math_expressions`: `(-x)^2`.

This is a pretty big/critical mathematical error/inaccuracy.

### Rephrasing

In mathematics, exponentation, i.e. powers (`^n`), bind stronger than signs (`-x`/`+x`). This is handled incorrectly in `math_expressions`.

## Example

`-4^2`:

* In a calculator / in mathematics: `= -16`.
* In `math_expressions`: `= 16`.

---

## Fix

I am unfortunately not familiar with the code in this library (i.e. how it is built) - otherwise, I would create a PR to fix this right away.  
I really want to get this fixed because it is a rather fundamental issue. If you can solve @fkleon, that would be amazing ❤️   
Otherwise, I would also appreciate if you hinted me at a potential fix for this, so that I can contribute it (I just want to get it fixed).

**Comment by fkleon** [comment]
Hi @creativecreatorormaybenot, thanks for this report. I agree with you that this is unexpected behaviour (for a maths library) and should be fixed.

Currently the unary minus has higher precedence than exponentiation, which is consistent with some spreadsheet applications (e.g. Excel) and a few programming languages (e.g. bc), but that doesn't seem to be the appropriate behaviour for a maths library.

This is a pretty easy fix that I'll get in soon.

**Comment by fkleon** [comment]
Published on pub as version 2.0.2. Let me know if that works for you.

**Comment by creativecreatorormaybenot** [comment]
@fkleon Thank you so much for the quick response ❤️ 

I will check it out today and let you know how it worked!

**Comment by creativecreatorormaybenot** [comment]
Tested and it works great 👌
