### ISSUE TITLE
floor and ceil function

### ISSUE THREAD

**Issue by kahtooei** [fkleon/math-expressions#56]
hi 
how can i use floor and ceil in my expression
i used ⌈x⌉ and ⌊x⌋ in my expression but it doesn't work

**Comment by fkleon** [comment]
Hi @kahtooei 

You can use the function names `floor` and `ceil` within an expression string.

For example:

```dart
Parser p = Parser();
Expression exp = p.parse('floor(x) + ceil(x)');
ContextModel cm = ContextModel()
  ..bindVariable(x, Number(math.pi));
double eval = exp.evaluate(EvaluationType.REAL, cm); // result is 7.0
```
