### ISSUE TITLE
How to solve simple linear equations?

### ISSUE THREAD

**Issue by thalisvilela** [fkleon/math-expressions#69]
I'm trying to solve some simple equations like "0.15*(183-y)+0.3y=0.2*183" is it possible to accomplish using this library?

**Comment by fkleon** [comment]
Hi @thalisvilela That's not possible with this library as it does not include an equation solver.

**Comment by thalisvilela** [comment]
Thanks very much for the reply! I've searched all internet, and haven't found any simple equation solver in Dart.

**Comment by fkleon** [comment]
Sounds like a it of a gap there :)

Hope you can find something suitable, or create your own.

**Comment by thalisvilela** [comment]
I would love to be able to create something, but unfortunately, math is way out of my skills set. I ended up simplifying the equation and doing regular math.
